### ISSUE TITLE
Does this repo contain full code?

### ISSUE THREAD

**Issue by tiangarin** [ygjwd12345/TransDA#1]
I notice that the model is not implemented as the paper depicts. And, is it feasible to train ResNetV2+ViT on a single gpu? I tried to run it on a 2080Ti, but it reported an "CUDA out of memory" error.

**Comment by ygjwd12345** [comment]
Would you mind pointing out which part is inconsistent with the paper? We run it in one 32G V100.

**Comment by ygjwd12345** [comment]
I believe we publish all the code.

**Comment by tiangarin** [comment]
I mean that I didn't see codes related to knowledge distillation in the training phase.

**Comment by tiangarin** [comment]
Sorry, I'm new to DA and thought image_target.py was test code, sorry about that.

**Comment by ygjwd12345** [comment]
It doesn't matter. Thanks for your asking.
